### ISSUE TITLE
Gloss doesn't preserve punctuation values from imported flextexts

### ISSUE THREAD

**Issue by somelinguist** [adamb924/Gloss#1]
Gloss strips the value of punctuation items from imported flextexts. As a result, it is unclear whether a given punctuation mark in the text is a period or comma or another mark after import.

Punctuation items after export from FLEx:
```xml
<word>
   <item type="punct" lang="qaa-x-xxx">.</item>
</word>
<word>
   <item type="punct" lang="qaa-x-xxx">,</item>
</word>
```

Punctuation items after import into Gloss (note they have the same id now):
```xml
<word abg:id="6">
   <item type="punct" lang="qaa-x-xxx"></item>
</word>
<word abg:id="6">
   <item type="punct" lang="qaa-x-xxx"></item>
</word>
```

Punctuation items after export from Gloss (note they still have the same id, and the value wasn't preserved at all):
```xml
<word abg:id="6">
   <item type="punct" lang="qaa-x-xxx"></item>
</word>
<word abg:id="6">
   <item type="punct" lang="qaa-x-xxx"></item>
</word>
```

Using the version downloaded on 9-11-2018.

**Comment by adamb924** [comment]
Yes, that was indeed an issue. I've fixed it now, so if you download and rebuild it should work.
